version: '3'
services:
  postgres:
    image: postgres
    container_name: my_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: demodb
      POSTGRES_USER: app1
      POSTGRES_PASSWORD:

